{{ $tls := fromYaml ( include "kep3633alt.webhookCerts" . ) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kep3633alt.webhookCertSecret" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kep3633alt.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  ca.crt: {{ $tls.caCert }}
  tls.crt: {{ $tls.clientCert }}
  tls.key: {{ $tls.clientKey }}
