{{ $tls := fromYaml ( include "kep3633alt.webhookCerts" . ) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kep3633alt.webhookCertSecret" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kep3633alt.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  ca.crt: {{ $tls.caCert }}
  tls.crt: {{ $tls.clientCert }}
  tls.key: {{ $tls.clientKey }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: kep3633alt-mutating
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      caBundle: {{ $tls.caCert }}
      service:
        name: {{ include "kep3633alt.fullname" . }}
        namespace: {{ .Release.Namespace }}
        path: '/'
        port: {{ .Values.service.port }}
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: kep3633alt.kubernetes.10h.in
    namespaceSelector: {}
    objectSelector:
      matchExpressions:
        - key: kep-3633-alt.10h.in/ignore
          operator: DoesNotExist
    rules:
      - apiGroups:
          - ''
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
    sideEffects: None
    timeoutSeconds: 1
